WITH CTE AS (
SELECT
    TO_TIMESTAMP(STARTED_AT) AS STARTED_AT,
    DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
    HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,
    {{ get_season('STARTED_AT') }} AS SEASON_OF_YEAR,
    {{ day_type('STARTED_AT')}} AS DAY_TYPE
    FROM
{{ ref('stg_bike') }}
    where STARTED_AT != 'started_at'
)

SELECT
*
FROM CTE